spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8086

order:
  kafka:
    bootstrap-servers: localhost:9092
    topic: order.capture
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      backs: all
      retries: 3
      linger-ms: 5
      batch-size: 16384
      compression-type: snappy

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5


  jackson:
    serialization:
      write-dates-as-timestamps: false